/**
 * OSKAR MedStat Researcher Dashboard Data Service
 * Decoupled data provider for researcher dashboard metrics, studies, and notifications.
 */

export const dashboardService = {
  getKpiMetrics: () => [
    {
      id: 'kpi_1',
      metricNumber: '01',
      labelKey: 'dashboard.researcher.kpi1Label',
      value: '14',
      subKey: 'dashboard.researcher.kpi1Sub',
      icon: 'folder_open',
      accentColor: 'teal',
    },
    {
      id: 'kpi_2',
      metricNumber: '02',
      labelKey: 'dashboard.researcher.kpi2Label',
      value: '1,525',
      subKey: 'dashboard.researcher.kpi2Sub',
      icon: 'groups',
      accentColor: 'sky',
    },
    {
      id: 'kpi_3',
      metricNumber: '03',
      statusBadge: 'APPROVED',
      labelKey: 'dashboard.researcher.kpi3Label',
      value: '96.4%',
      subKey: 'dashboard.researcher.kpi3Sub',
      icon: 'verified',
      accentColor: 'emerald',
    },
    {
      id: 'kpi_4',
      metricNumber: '04',
      statusBadge: 'EXPORTS',
      labelKey: 'dashboard.researcher.kpi4Label',
      value: '28',
      subKey: 'dashboard.researcher.kpi4Sub',
      icon: 'table_chart',
      accentColor: 'indigo',
    },
  ],

  getActiveStudies: () => [
    {
      id: 'STD-2026-001',
      title: 'Triple-Drug Immunotherapy in Renal Cell Carcinoma',
      methodologyKey: 'dashboard.researcher.r1Type',
      statusKey: 'dashboard.researcher.statusActive',
      statusVariant: 'teal',
      enrolled: '240 / 350',
      progress: 68,
      actionKey: 'dashboard.researcher.btnOpenStudy',
      actionRoute: '/researcher/studies/new',
      actionIcon: 'visibility',
    },
    {
      id: 'STD-2026-002',
      title: 'Cardiac Biomarkers in Acute Myocarditis Patients',
      methodologyKey: 'dashboard.researcher.r2Type',
      statusKey: 'dashboard.researcher.statusStatistical',
      statusVariant: 'sky',
      enrolled: '1,200 / 1,200',
      progress: 85,
      actionKey: 'dashboard.researcher.btnRunEngine',
      actionRoute: '/researcher/statistics',
      actionIcon: 'analytics',
    },
    {
      id: 'STD-2026-003',
      title: 'Marginal Bone Loss Evaluation in Dental Implants',
      methodologyKey: 'dashboard.researcher.r3Type',
      statusKey: 'dashboard.researcher.statusComplete',
      statusVariant: 'emerald',
      enrolled: '500 / 500',
      progress: 100,
      actionKey: 'dashboard.researcher.btnExportApa',
      actionRoute: '/researcher/studies',
      actionIcon: 'file_download',
    },
  ],

  getDashboardNotifications: () => [
    {
      id: 'notif_1',
      studyId: 'Study STD-2026-003',
      typeKey: 'dashboard.researcher.ev1Type',
      titleKey: 'dashboard.researcher.ev1Title',
      descKey: 'dashboard.researcher.ev1Desc',
      ctaKey: 'dashboard.researcher.ev1Cta',
      badgeKey: 'dashboard.researcher.badgeActionRequired',
      author: 'Dr. Marcus Vance • External Reviewer',
      timestampEn: '2 hours ago',
      timestampAr: 'منذ ساعتين',
      icon: 'rate_review',
      colorVariant: 'red',
      route: '/researcher/studies',
    },
    {
      id: 'notif_2',
      studyId: 'Study STD-2026-001',
      typeKey: 'dashboard.researcher.ev2Type',
      titleKey: 'dashboard.researcher.ev2Title',
      descKey: 'dashboard.researcher.ev2Desc',
      ctaKey: 'dashboard.researcher.ev2Cta',
      badgeKey: 'dashboard.researcher.badgeActionRequired',
      author: 'Prof. Abdullah Al-Qahtani • Department Chair',
      timestampEn: 'Yesterday',
      timestampAr: 'أمس',
      icon: 'supervisor_account',
      colorVariant: 'amber',
      route: '/researcher/studies',
    },
    {
      id: 'notif_3',
      studyId: 'Study STD-2026-002',
      typeKey: 'dashboard.researcher.ev3Type',
      titleKey: 'dashboard.researcher.ev3Title',
      descKey: 'dashboard.researcher.ev3Desc',
      ctaKey: 'dashboard.researcher.ev3Cta',
      badgeKey: 'dashboard.researcher.badgeCompleted',
      author: 'OSKAR Biostatistical Engine',
      timestampEn: 'Yesterday',
      timestampAr: 'أمس',
      icon: 'analytics',
      colorVariant: 'sky',
      route: '/researcher/statistics',
    },
    {
      id: 'notif_4',
      studyId: 'Protocol IRB-KFMC-2026-88',
      typeKey: 'dashboard.researcher.ev4Type',
      titleKey: 'dashboard.researcher.ev4Title',
      descKey: 'dashboard.researcher.ev4Desc',
      ctaKey: 'dashboard.researcher.ev4Cta',
      badgeKey: 'dashboard.researcher.badgeApproved',
      author: 'Institutional Review Board (IRB)',
      timestampEn: '3 days ago',
      timestampAr: 'منذ 3 أيام',
      icon: 'verified',
      colorVariant: 'emerald',
      route: '/researcher/studies',
    },
  ],

  getAiCreditsInfo: () => ({
    used: 100,
    total: 100,
    percentage: 100,
  }),
};

export default dashboardService;
