export const COMMERCIAL_SERVICES = [
  {
    id: 'rct_service',
    title: 'Randomized Controlled Trial (RCT)',
    price: 125,
    currency: '$',
    period: 'per study',
    description: 'Experimental Clinical Trials with SPIRIT 2025 Protocol compliance, eCRF generation, sample randomization, and SPSS export.',
    features: [
      'SPIRIT 2025 Protocol Engine',
      'eCRF Form Builder & Ingestion',
      'Sample Size & Power Analysis',
      'Randomization & Visit Management',
      'SPSS & CSV Dataset Export',
    ],
    popular: true,
    badge: 'Gold Standard',
  },
  {
    id: 'retro_service',
    title: 'Retrospective Study',
    price: 65,
    currency: '$',
    period: 'per study',
    description: 'Historical Data Ingestion (1,000 Extraction Credits + 100 Free Trial Credits) with RECORD & STROBE compliance.',
    features: [
      '1,000 Extraction Credits Included',
      '100 Free Trial Extractions',
      'AI Variable Dictionary Mapping',
      'Duplicate Scanner & Exclude/Merge',
      'Multi-Sheet Excel (.xlsx) & SPSS Export',
    ],
    popular: false,
  },
  {
    id: 'cohort_service',
    title: 'Prospective Cohort Study',
    price: 85,
    currency: '$',
    period: 'per study',
    description: 'Longitudinal follow-up tracking across baseline (T0) and visits (T1..Tn), eligibility AI Guard, and STROBE compliance.',
    features: [
      'Baseline (T0) & Visit Schedule (T1..Tn)',
      'Eligibility AI Guard Checklist',
      'Digital E-Signature Pad & Consent',
      '5-Sheet Excel Workbook Export',
      'External Reviewer Package Access',
    ],
    popular: false,
  },
  {
    id: 'cross_sectional_service',
    title: 'Cross-Sectional Survey',
    price: 35,
    currency: '$',
    period: 'per study',
    description: 'Single timepoint survey assessment with Questionnaire Builder, validated instruments (OHIP, GAD-7), and Cronbach Alpha calculator.',
    features: [
      'Questionnaire Builder & Validated Instruments',
      'Cronbach Alpha Reliability Calculator (α ≥ 0.70)',
      'Multi-Channel QR, Link & Email Distribution',
      'Multi-Sheet Excel (.xlsx) & SPSS Syntax (.sps)',
    ],
    popular: false,
  },
  {
    id: 'basic_sample_size',
    title: 'Basic Sample Size Calculation',
    price: 20,
    currency: '$',
    period: 'per calculation',
    description: 'Standard biostatistical power and sample size determination for t-tests, proportions, and cross-sectional surveys.',
    features: [
      'Independent & Paired t-Test Models',
      'Two-Proportion Z-Test Calculator',
      'Cross-Sectional Margin of Error Formula',
      'Dropout-Adjusted Sample N Engine',
    ],
    popular: false,
  },
  {
    id: 'advanced_sample_size',
    title: 'Advanced Sample Size Calculation',
    price: 35,
    currency: '$',
    period: 'per calculation',
    description: 'Complex multi-arm ANOVA, Chi-Square contingency, non-inferiority, and survival analysis sample size modeling.',
    features: [
      'One-Way & Factorial ANOVA Models',
      'Chi-Square Contingency W Engine',
      'Non-Inferiority & Superiority Bounds',
      'Statistical Formula Citation Generator',
    ],
    popular: false,
  },
  {
    id: 'basic_stat_analysis',
    title: 'Basic Statistical Analysis',
    price: 50,
    currency: '$',
    period: 'per analysis',
    description: 'Descriptive statistics, normality testing (Shapiro-Wilk), parametric t-tests, and frequency distributions.',
    features: [
      'Automated Descriptive Summary Tables',
      'Normality & Homogeneity Tests',
      'Parametric & Non-Parametric Tests',
      'APA & Medical Journal Output',
    ],
    popular: false,
  },
  {
    id: 'inferential_stat_analysis',
    title: 'Inferential Statistical Analysis',
    price: 80,
    currency: '$',
    period: 'per analysis',
    description: 'Multiple linear regression, logistic regression, ANOVA with post-hoc Tukey tests, and odds ratio estimations.',
    features: [
      'Multiple Linear & Logistic Regression',
      'Post-Hoc Pairwise Comparisons',
      'Adjusted Odds Ratio (aOR) Calculator',
      'Model Fit Statistics (R², AIC, BIC)',
    ],
    popular: false,
  },
  {
    id: 'advanced_stat_analysis',
    title: 'Advanced Statistical Analysis',
    price: 130,
    currency: '$',
    period: 'per analysis',
    description: 'Cox proportional hazards, Kaplan-Meier survival curves, multivariate GEE models, and propensity score matching.',
    features: [
      'Kaplan-Meier & Survival Curves',
      'Cox Proportional Hazard Engine',
      'Propensity Score Matching (PSM)',
      'High-Resolution Vector SVG Exports',
    ],
    popular: false,
  },
];

export const getBillingServices = () => COMMERCIAL_SERVICES;

export const billingService = {
  getServices: getBillingServices,
  getActivePlan: () => ({
    name: 'Institutional Researcher Tier',
    status: 'active',
    renewalDate: '2026-12-31',
    creditsRemaining: 18,
  }),
};

export default billingService;
